---
# tasks file for vim-plugins
#
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: install git
  package: name=git

- name: git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    update: no

- name: make usre colors exist
  file: dest={{ ansible_env.HOME }}/.vim/colors state=directory

- name: copy color scheme
  copy: src=solarized.vim dest={{ ansible_env.HOME }}/.vim/colors

- name: copy .vimrc
  template: src=vimrc dest={{ ansible_env.HOME }}/.vimrc

  #- name: update colorama
  #  pip: name=colorama
  #  become: yes

- name: install jedi
  pip: name=jedi
  become: yes

- name: install ctags
  package: name=ctags
  become: yes

- name: install cscope
  package: name=cscope
  become: yes

- name: install sshfs
  package: name={{ sshfs }}
  become: yes
  when: ansible_distribution == 'Debian'

- name: install plugins
  shell: vim +PluginInstall +qall
