---
# tasks file for vim-plugins
#
- name: install git
  package: name=git

- name: git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    update: no

- name: make usre colors exist
  file: dest={{ ansible_env.HOME }}/.vim/colors state=directory

- name: copy color scheme
  copy: src=solarized.vim dest={{ ansible_env.HOME }}/.vim/colors

- name: copy .vimrc
  template: src=vimrc dest={{ ansible_env.HOME }}/.vimrc

  #- name: update colorama
  #  pip: name=colorama
  #  become: yes

- name: download pip
  shell: wget https://bootstrap.pypa.io/get-pip.py -O /root/get-pip.py creates=/root/get-pip.py

- name: check whether pip installed
  shell: pip
  register: rt
  ignore_errors: yes

- name: install pip
  shell: python /root/get-pip.py
  when: rt.rc != 0

- name: install jedi
  pip: name=jedi
  become: yes

- name: install ctags
  package: name=ctags
  become: yes

- name: install cscope
  package: name=cscope
  become: yes

- name: install sshfs
  package: name={{ sshfs }}
  become: yes
  when: ansible_distribution == 'Debian'

- name: install plugins
  shell: vim +PluginInstall +qall
