---
# tasks file for loopback-device
#
- name: create device image
  command: fallocate -l {{ device_size }} {{ device_file }} creates={{ device_file }}

- name: copy losetup script
  template:
    src: losetup.conf.j2
    dest: /usr/lib/systemd/scripts/losetup-{{ device_name }}.sh
    mode: 755

- name: copy losetup service
  template:
    src: loopback-device.service.j2
    dest: /usr/lib/systemd/system/loopback-{{ device_name }}.service

- name: setup loopback device
  service:
    name: loopback-{{ device_name }}.service
    state: started
