---
# tasks file for loopback-device
#
- name: create device image
  command: fallocate -l {{ device_size }} {{ device_file }} creates={{ device_file }}
  tags:
    - loopback

- name: copy losetup script
  template:
    src: losetup.conf.j2
    dest: /usr/lib/systemd/scripts/losetup-{{ device_name }}.sh
  tags:
    - loopback

- name: copy losetup service
  template:
    src: loopback-device.service.j2
    dest: /usr/lib/systemd/system/loopback-{{ device_name }}.service
  register: result
  tags:
    - loopback

- name: setup loopback device
  service:
    name: loopback-{{ device_name }}.service
    state: started
  when: result|changed
  tags:
    - loopback
