---
# tasks file for youcompleteme
#

- name: install cmake
  apt: name=cmake state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install python-dev
  apt: name=python-dev state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install python3-dev
  apt: name=python3-dev state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install git
  apt: name=git state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: git clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME}}/.vim/bundle/Vundle.vim"
    update: no

- name: git clone YCM
  git:
    repo: "https://github.com/Valloric/YouCompleteMe.git"
    dest: "{{ ansible_env.HOME}}/.vim/bundle/YouCompleteMe"
    recursive: yes
    track_submodules: yes
    update: no

- name: init submodule for YCM
  shell: "cd {{ ansible_env.HOME}}/.vim/bundle/YouCompleteMe && git submodule update --init --recursive"

- debug: var=clang
- name: compile YCM with clang
  shell: "cd {{ ansible_env.HOME}}/.vim/bundle/YouCompleteMe && ./install.py --clang-completer"
  when: clang
- name: compile YCM without clang
  shell: "cd {{ ansible_env.HOME}}/.vim/bundle/YouCompleteMe && ./install.py"
  when: clang is undefined or not clang 
